config/article/urls.py
from .views import index, create, retrieve, update, delete, create_account, index_account, retrieve_account, update_account, delete_account, amount_ajax
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'article'

urlpatterns = [
    path('', index, name='list'),
    path('create/', create, name='create'),
    path('article/<int:pk>/', retrieve, name='retrieve'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('create_account/', create_account, name='create_account'),
    path('index_account/', index_account, name='index_account'),
    path('account/<int:pk>/', retrieve_account, name='retrieve_account'),
    path('update_account/<int:pk>/',update_account, name='update_account'),
    path('delete_account/<int:pk>/',delete_account, name='delete_account'),
    path('amount/',amount_ajax, name='amount_ajax'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/article/models.py
from django.db import models
from django.shortcuts import render, redirect, reverse

class Account(models.Model):
    name = models.CharField(max_length=25)
    call = models.CharField(max_length=25)
    address = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.name)

class Article(models.Model):
    title = models.CharField(max_length=25, verbose_name='상품 이름')
    content = models.TextField(verbose_name='상품 설명')
    photo = models.ImageField(blank=True, upload_to="image")
    price = models.CharField(default=1, max_length=25, verbose_name='가격')
    amount = models.PositiveIntegerField(default=1, verbose_name='수량')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, default=1, verbose_name='거래처')

    def get_absolute_url(self):  # new
        return reverse('article:retrieve', args=[str(self.id)])

    def __str__(self):
        return '{}'.format(self.title)

config/article/forms.py
from django import forms
from .models import Account,Article

class ItemForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

config/article/views.py
from django.shortcuts import render, redirect, reverse
from .models import Article,Account
from .forms import ItemForm
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView
from django.views.decorators.http import require_POST
from django.http import JsonResponse

def index(request):
    queryset = Article.objects.all()
    context = {
        'articles': queryset,
    }
    return render(request, 'article/index.html', context=context)

def retrieve(request, pk):
    article = Article.objects.get(id=pk)

    context = {
        'article': article,
    }

    return render(request, 'article/retrieve.html', context=context)

# def create(request, article=None):
#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES, instance=article)
#         if form.is_valid():
#             article = form.save()
#             pk = article.id
#             url = reverse('article:retrieve', kwargs={'pk': pk})
#             return redirect(to=url)
#     else:
#         form = ItemForm(instance=article)
#     return render(request, 'article/create.html', {
#         'form':form,
#     })
#
# def update(request, pk):
#     article = get_object_or_404(Article, pk=pk)
#     # Get
#     if request.method == 'GET':
#         form = ItemForm(instance=article)
#         return render(request, 'article/create.html', {
#             'form': form,
#         })
#
#     else:
#         form = ItemForm(request.POST, request.FILES, instance=article)
#         if form.is_valid():
#             article = form.save()
#             return(article)

create = CreateView.as_view(model=Article, form_class=ItemForm)

update = UpdateView.as_view(model=Article, form_class=ItemForm)



def delete(request, pk):
    article = Article.objects.get(id=pk)
    article.delete()

    url = reverse('article:list')
    return redirect(to=url)


def create_account(request):
    # Get
    if request.method == 'GET':
        return render(request, 'article/create_account.html', context={})
    # Post
    name = request.POST['name']
    call = request.POST['call']
    address = request.POST['address']
    account = Account.objects.create(name=name, call=call, address=address)
    pk = account.id
    url = reverse('article:index_account')
    return redirect(to=url)


def index_account(request):
    queryset = Account.objects.all()
    context = {
        'accounts': queryset,
    }
    return render(request, 'article/index_account.html', context=context)


def retrieve_account(request, pk):
    account = Account.objects.get(id=pk)
    article = str(account.article_set.all()).replace('QuerySet','').replace('Article:','')

    context = {
        'account': account,
        'article': article,
    }

    return render(request, 'article/retrieve_account.html', context=context)


def update_account(request, pk):
    account = Account.objects.get(id=pk)
    # Get
    if request.method == 'GET':
        context = {
            'account': account,
        }
        return render(request, 'article/update_account.html', context=context)

    # POST
    # request 에서 받아온 내용들
    name = request.POST['name']
    call = request.POST['call']
    address = request.POST['address']

    # 데이터베이스에 바꿀 내용들
    account.name = name
    account.call = call
    account.address = address
    account.save()

    url = reverse('article:retrieve_account', kwargs={'pk': pk})
    return redirect(to=url)


def delete_account(request, pk):
    account = Account.objects.get(id=pk)
    account.delete()

    url = reverse('article:index_account')
    return redirect(to=url)

@require_POST
def amount_ajax(request):
    pk = request.POST.get("pk")
    status = request.POST.get("status")
    article = get_object_or_404(Article, pk=pk)

    if status == "plus":
        article.amount += 1
    else:
        if article.amount > 0:
            article.amount -= 1
        else:
            url = reverse('article:list')
            redirect(to=url)
    article.save()
    ctx = {
        "amount": article.amount,
    }
    return JsonResponse(ctx)

config/article/templates/article/article_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>상품 등록하기</title>
    <style>
        .inputbutton {
            border: #19865C solid 3px;
            border-radius: 10px;
            background-color: #19865C;
            color: white;
        }
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>
<h1>상품 등록하기</h1>

<form action="{% url 'article:create'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <table class="form_table">
        {{form.as_table}}

    </table>

    <input type="submit" class="inputbutton" value="저장" />
</form>

</body>
</html>

config/article/templates/article/create_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>거래처 등록하기</title>
    <style>
        .inputbutton {
            border: #19865C solid 3px;
            border-radius: 10px;
            background-color: #19865C;
            color: white;
        }
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>
<h1>거래처 등록하기</h1>

<form action="{% url 'article:create_account'%}" method="POST">
    {% csrf_token %}
    Name:
    <input type="text" name="name" />
    <br>
    Call:
    <input type="text" name="call"/>
    <br>
    Address:
    <input type="text" name="address"/>
    <br>
    <input type="submit" class="inputbutton" value="저장" />
</form>
</body>
</html>

config/article/templates/article/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>메인페이지</title>
    <style>
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
        .content_wrap {
            display: inline-block;
            width: 100%;
            text-align: center;
        }
        .item_wrap{
            display: inline-block;
            margin: 0 auto;
            width: 85%;
        }
        .item {
            float: left;
            padding: 5%;
        }
    </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script>
        function clickButton (pk, status) {
            console.log(pk); //확인용
            console.log(status);
            $.ajax({
                type: "post",
                url: "{% url 'article:amount_ajax' %}",
                data: {"pk": pk, "status": status, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                success: function (response) {
                    console.log("success");
                    let a = document.getElementById(`amount-${pk}`);
                    a.innerText = `재고: ${response.amount}`;
                }, error: function (request, status, error) { // 통신 실패
                    alert("fail");
                },
            })
        }
    </script>
</head>
<body>

<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>

</div>
<div class="content_wrap">
<h1>Item List</h1>
<h3>상품 목록 페이지 입니다.</h3>
    <br>
    <hr>
<div class="item_wrap">
{% for article in articles %}
    <div class="item">
        <a href="{% url 'article:retrieve' pk=article.pk %}"><{{ article.title }}></a>
        <p>
        {% if article.photo %}
        <img src="{{article.photo.url}}" alt="">
        {% endif %}
        </p>
        <p>가격: {{article.price}}</p>
        <p id="amount-{{ article.pk }}">재고: {{article.amount}}</p>
        <input type="submit" value="+" class="plusbutton" onclick="clickButton({{article.pk}},'plus')">
        <input type="submit" value="-" class="minusbutton" onclick="clickButton({{article.pk}},'minus')">
    </div>
{% endfor %}
</div>
</div>
</body>
</html>

config/article/templates/article/index_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>메인페이지</title>
    <style>
        .content_wrap {
            display: inline-block;
            width: 100%;
            text-align: center;
        }
        .item_wrap{
            display: inline-block;
            margin: 0 auto;
            width: 85%;
        }
        .item {
            float: left;
            padding: 5%;
        }
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>

<div class="content_wrap">
<h1>Account List</h1>
<h3>거래처 목록 페이지 입니다.</h3>
    <br>
    <hr>
<div class="item_wrap">
{% for account in accounts %}
    <div class="item">
        <a href="{% url 'article:retrieve_account' pk=account.pk %}"><{{ account.name }}></a>
        <p>전화번호: {{account.call}}</p>
        <p>주소: {{account.address}}</p>
    </div>
{% endfor %}
</div>
</div>
</body>
</html>

config/article/templates/article/retrieve.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .smallbutton {
            border: #19865C solid 3px;
            border-radius: 10px;
            background-color: #19865C;
            color: white;
            text-decoration: none;
        }
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>
<h1>Item Detail</h1>
<h3>상품 세부내용 페이지 입니다.</h3>
<p>상품 이름: {{article.title}}</p>
<p>상품 가격: {{article.price}}</p>
<p>상품 설명: {{article.content}}</p>
<p>거래처: {{article.account}}</p>
<p>
{% if article.photo %}

<img src="{{article.photo.url}}" alt="">
{% endif %}
</p>
<a class="smallbutton" href="{% url 'article:update' pk=article.pk %}">수정하기</a>
<a class="smallbutton" href="{% url 'article:delete' pk=article.pk %}">삭제하기</a>
<a class="smallbutton" href="{% url 'article:list' %}">목록으로</a>
</body>
</html>

config/article/templates/article/retrieve_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .smallbutton {
            border: #19865C solid 3px;
            border-radius: 10px;
            background-color: #19865C;
            color: white;
            text-decoration: none;
        }
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>
<h1>Account Detail</h1>
<h3>거래처 세부내용 페이지 입니다.</h3>
<p>거래처 이름: {{account.name}}</p>
<p>거래처 번호: {{account.call}}</p>
<p>거래처 주소: {{account.address}}</p>
<p>거래되는 상품: {{article}}</p>
<a class="smallbutton" href="{% url 'article:update_account' pk=account.pk %}">수정하기</a>
<a class="smallbutton" href="{% url 'article:delete_account' pk=account.pk %}">삭제하기</a>
<a class="smallbutton" href="{% url 'article:index_account' %}">거래처 목록으로</a>
</body>
</html>

config/article/templates/article/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>상품 수정하기</title>
    <style>
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>
<h1>상품 수정하기</h1>

<form action="{% url 'article:update' pk=article.pk %}" method="POST">
    {% csrf_token %}
    Title:
    <input type="text" name="title" value="{{article.title}}"/>
    <br>
    Image:
    <br>
    Content:
    <textarea name="content">{{article.content}}</textarea>
    <br>
    Price:
    <input type="text" name="price" value="{{article.price}}"/>
    <br>
    Amount:
    <input type="text" name="amount" value="{{article.amount}}"/>
    <br>
    <input type="submit" value="수정" />
</form>

</body>
</html>

config/article/templates/article/update_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>거래처 수정하기</title>
    <style>
        .nav_bar {
            background-color: #4f4f4f;
            display: inline-block;
            width: 100%;
            height: 50px;
        }
        .nav_bar a {
            color: white;
            font-size: 15px;
            margin: 1%;
        }
        .logo {
            float: left;
        }
        .itemplus {
            float: right;
        }
        .accountplus {
            float: right;
        }
        .accountmanage {
            float: right;
        }
    </style>
</head>
<body>
<div class="nav_bar">
    <a class="logo" href="{% url 'article:list' %}">Inventory Manage</a>
    <a class="accountmanage" href="{% url 'article:index_account' %}">거래처 관리</a>
    <a class="accountplus" href="{% url 'article:create_account' %}">거래처 등록</a>
    <a class="itemplus" href="{% url 'article:create'%}">상품 등록</a>
</div>
<h1>거래처 수정하기</h1>

<form action="{% url 'article:update_account' pk=account.pk %}" method="POST">
    {% csrf_token %}
    Name:
    <input type="text" name="name" value="{{account.name}}"/>
    <br>
    Call:
    <input type="text" name="call" value="{{account.call}}"/>
    <br>
    Address:
    <input type="text" name="address" value="{{account.address}}"/>
    <br>
    <input type="submit" value="수정" />
</form>

</body>
</html>